security:
    firewalls:
        login:
            pattern:  ^/login$
            security: false
        
        demo:
            pattern:  ^/demo/secured/login$
            security: false
            
            
        secured_area:
            pattern:    ^/
            anonymous: ~
#            http_basic:
#               realm: "Secured Demo Area"
            form_login: 
                login_path:  _my_login
                check_path:  _my_login_check
                always_use_default_target_path: true
                default_target_path: /homepage
                
            logout:
                path:   _my_logout
                target: _my_login
          
                
                
#        nowshad_controller:
#            pattern:  ^/nowshad/mycontact
#            form_login:
#                login_path: _my_login
#                check_path: _my_login_check
                
#        qnowshad_controller_test2:
#            pattern:  ^/nowshad/test2
#            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"
#                

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        chain_provider:
          chain:
            providers: [in_memory, user_db]
            
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: 'ROLE_USER' }
                    admin: { password: admin, roles: ['ROLE_ADMIN', 'ROLE_FLEET', 'ROLE_USER'] }
                    nowshad: { password: nowshad, roles: 'ROLE_FLEET' }
        user_db:
          entity: {class: Expense\StoreBundle\Entity\User, property: username}

    encoders:
        Expense\StoreBundle\Entity\User: 
                algorithm: sha1
                iterations: 1
                encode_as_base64: false
        Symfony\Component\Security\Core\User\User: plaintext