parameters:
#    expense_site.example.class: Expense\SiteBundle\Example

services:
#    expense_site.example:
#        class: %expense_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
