parameters:
#    expense_store.example.class: Expense\StoreBundle\Example

services:
#    expense_store.example:
#        class: %expense_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
